# Generated by Django 5.1.3 on 2025-05-11 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=128)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(choices=[("male", "Male"), ("female", "Female")], max_length=6)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("bio", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="kids", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-date_of_birth"],
            },
        ),
    ]
