repos:
  # https://docs.astral.sh/ruff/integrations/#pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
  # https://commitizen-tools.github.io/commitizen/tutorials/auto_check/#method-1-using-pre-commit-hook-frameworks-recommended
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.10
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
