name: Prod deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    name: "Deployment"
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
