name: Update develop branch

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  update-branches:
    runs-on: ubuntu-latest
    name: "Update develop branch"
    steps:
        - name: Check out
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            token: "${{ secrets.GITHUB_TOKEN }}"
            fetch-depth: 0
        - name: Setup Git User
          run: |
            git config user.email "janosmatula@yahoo.com"
            git config user.name "vasalodeszka"
        - name: Update develop branch
          run: |
            git fetch
            git checkout develop
            git pull
            git merge origin/main
            git push